Feature/conjugator options
lenguasdearagon/aragonario-frontend pull request #8
Opened 2021-07-07 12:32 UTC by dunetna

2021-07-19 09:10 UTC, slamora requested changes
Everything is working as expected! Just a two comments:
1. Regarding to input style, AFAIK, will be more flexible follow the approach of hidding default item and customize a new one [as suggested in W3C example](https://www.w3schools.com/howto/howto_css_custom_checkbox.asp).
2. Remove "Grafía" option, as DGPL should we always used to be homogeneous with the rest of the content.

2021-07-19 15:33 UTC, slamora requested changes

2021-07-19 15:33 UTC, slamora commented on linguatec_lexicon_frontend/forms.py
> +        label="Rematanza d'os participios", choices=REMATANZA_CHOICES, widget=forms.RadioSelect
```suggestion
        label="Rematanza d'os partizipios", choices=REMATANZA_CHOICES, widget=forms.RadioSelect
```

2021-07-20 09:39 UTC, dunetna commented
> Everything is working as expected! Just a two comments:
> 
>     1. Regarding to input style, AFAIK, will be more flexible follow the approach of hidding default item and customize a new one [as suggested in W3C example](https://www.w3schools.com/howto/howto_css_custom_checkbox.asp).

Done at https://github.com/lenguasdearagon/aragonario-frontend/pull/8/commits/b24379c21e85753e513da4c46100ec9384fe2499

>     2. Remove "Grafía" option, as DGPL should we always used to be homogeneous with the rest of the content.
Done at https://github.com/lenguasdearagon/aragonario-frontend/pull/8/commits/39023c49ee0296eb225bd0dcbfea5bdb551c658d

2021-07-20 13:18 UTC, slamora requested changes
Why don't use col-12 and col-3 to use all the width available?

2021-07-20 13:33 UTC, dunetna commented
> Why don't use col-12 and col-3 to use all the width available?

Because I'm not the best front-end developer XDD
Fixed using col-12 and CSS right margin :-)

2021-07-20 14:21 UTC, slamora approved these changes

2021-07-20 14:21 UTC, merged